<a href="https://colab.research.google.com/github/Sumitsharma12321/GDP-Analysis/blob/main/GDP_Growth_of_Country.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df = pd.read_csv('gdp.csv')
df.head()

  Country Name Country Code  Year         Value
0   Arab World          ARB  1968  2.576068e+10
1   Arab World          ARB  1969  2.843420e+10
2   Arab World          ARB  1970  3.138550e+10
3   Arab World          ARB  1971  3.642691e+10
4   Arab World          ARB  1972  4.331606e+10

# **Finding GDP Growth of a Country**

In [15]:
df_In = df[df['Country Name'] == 'India']

data = df_In.values

gdp_change = [0]

for i in range(1,len(data)):

    prev = data[i-1][3]
    cur = data[i][3]

    gdp_change.append(round(((cur - prev) / prev)*100,2))

df_In = df_In.assign(GDP = gdp_change)

# **Finding GDP Growth of Every Country**

In [16]:
final_data = []

for country_name in df['Country Name'].unique():

    df_pr = df[df['Country Name'] == country_name]

    data = df_pr.values
    gdp_change = [0]

    for i in range(1,len(data)):

        prev = data[i-1][3]
        cur = data[i][3]

        gdp_change.append(round(((cur - prev) / prev)*100,2))

    df_pr = df_pr.assign(GDP = gdp_change)
    final_data.append(df_pr)

In [17]:
df = pd.concat(final_data , axis =0)

In [18]:
df

      Country Name Country Code  Year         Value    GDP
0       Arab World          ARB  1968  2.576068e+10   0.00
1       Arab World          ARB  1969  2.843420e+10  10.38
2       Arab World          ARB  1970  3.138550e+10  10.38
3       Arab World          ARB  1971  3.642691e+10  16.06
4       Arab World          ARB  1972  4.331606e+10  18.91
...            ...          ...   ...           ...    ...
11502     Zimbabwe          ZWE  2012  1.424249e+10  17.72
11503     Zimbabwe          ZWE  2013  1.545177e+10   8.49
11504     Zimbabwe          ZWE  2014  1.589105e+10   2.84
11505     Zimbabwe          ZWE  2015  1.630467e+10   2.60
11506     Zimbabwe          ZWE  2016  1.661996e+10   1.93

[11507 rows x 5 columns]

In [22]:
df.groupby('Country Name').max()['Value'].sort_values(ascending = False).head(30)

Country Name
World                                                   7.904923e+13
High income                                             5.036240e+13
OECD members                                            4.937008e+13
Post-demographic dividend                               4.673504e+13
IDA & IBRD total                                        2.948247e+13
Low & middle income                                     2.870476e+13
Middle income                                           2.829277e+13
IBRD only                                               2.739661e+13
Europe & Central Asia                                   2.365470e+13
East Asia & Pacific                                     2.248043e+13
Upper middle income                                     2.221220e+13
North America                                           2.016030e+13
Late-demographic dividend                               1.970310e+13
European Union                                          1.913667e+13
United States                                           1.862448e+13
Euro area                                               1.411818e+13
East Asia & Pacific (excluding high income)             1.351244e+13
East Asia & Pacific (IDA & IBRD countries)              1.348649e+13
China                                                   1.119915e+13
Early-demographic dividend                              1.052987e+13
Latin America & Caribbean                               6.391550e+12
Lower middle income                                     6.263373e+12
Japan                                                   6.203213e+12
Latin America & the Caribbean (IDA & IBRD countries)    6.171392e+12
Latin America & Caribbean (excluding high income)       5.905518e+12
Europe & Central Asia (IDA & IBRD countries)            4.893444e+12
Europe & Central Asia (excluding high income)           4.369243e+12
Germany                                                 3.890607e+12
Middle East & North Africa                              3.563559e+12
United Kingdom                                          3.074360e+12
Name: Value, dtype: float64